routes:
  /links/rss/:
    template: links/rss
    content_type: text/xml

  /rss/:
    template: home/rss
    content_type: text/xml

collections:
  /:
    permalink: /{year}/{month}/{day}/{slug}/
    template: index
    filter: primary_tag:-links

  /links/:
    permalink: /links/{year}/{month}/{day}/{slug}/
    template: links
    filter: primary_tag:links
    data: tag.links

taxonomies:
  tag: /tag/{slug}/
  author: /author/{slug}/
